---
name: Eslint test

on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: make lint
      run: make lint
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: apps # only if a different glob is needed, default: src

